before_install:
- ./build-tools/install-protobuf.sh
env: MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=512M"
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn -B clean install package -DskipTests=true -Dmaven.javadoc.skip=true
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: required
